services:

  exchanger-data:
    container_name: data-exchange
    image: data-exchanger
    build:
      context: ./Exchanger-data
      dockerfile: exchanger_data.dockerfile
    ports:
      - "9000:9000"
    networks:
      - redis-net
    depends_on:
      - redis-data
      - postgres-data
    restart: always

  setting-data:
    container_name: settings-exchange
    image: settings-exchange
    build:
      context: ./Settings
      dockerfile: settings.dockerfile
    ports:
      - "5010:5010"
    networks:
      - redis-net
      - postgres-net
    depends_on:
      - redis-data
      - postgres-data
    restart: always

  parser-course:
    container_name: parser-course-exchange
    image: parser-course
    build:
      context: ./Parser-course
      dockerfile: parser-course.dockerfile
    ports:
      - "9000"
    networks:
      - redis-net
    depends_on:
      - redis-data
      - postgres-data
      - setting-data
    restart: always

  redis-data:
    container_name: redis-exchange
    image: redis:6.2-alpine
    ports:
      - "6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    networks:
      - redis-net
    restart: always

  postgres-data:
    container_name: postgres-exchange
    image: postgresql
    build:
      context: ./Database
      dockerfile: postgresql.dockerfile
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=5s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    volumes:
      - postgres:/opt/foo
    environment:
      POSTGRES_DB: exchange
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      PGDATA: /data/postgres
    ports:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docker -d exchange"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
    networks:
      - postgres-net
    restart: unless-stopped

networks:
  postgres-net:
    driver: bridge
  redis-net:
    driver: bridge
  auto-dr:
    driver: bridge

volumes:
    postgres:
      driver : local
    redis-data:
      driver : local

