from markets.binanceP2P import Binance2P2
from markets.binanceSpot import BinanceSpot
from markets.huobiP2P import HuobiP2P
from markets.okexP2P import Okex2P2
from markets.pexpayP2P import Pexpay2P2
from markets.market import MarketP2P
from markets.okexSpot import OkexSpot
from markets.huobiSpot import HuobiSpot
from markets.pexpaySpot import PexpaySpot
from markets.bybitP2P import ByBit2P2