CREATE USER ownerdb WITH PASSWORD 'X$Oi815H%nd*FLyB!9v%';
GRANT CONNECT ON DATABASE crypto TO ownerdb;
ALTER USER ownerdb WITH SUPERUSER;

CREATE USER admindb WITH PASSWORD 'X$Oi815H%nd*FLyB!9v%';
GRANT CONNECT ON DATABASE crypto TO admindb;
ALTER USER admindb WITH SUPERUSER;

CREATE USER operatordb WITH PASSWORD 'X$Oi815H%nd*FLyB!9v%';
GRANT CONNECT ON DATABASE crypto TO operatordb;
ALTER USER operatordb WITH SUPERUSER;